export {default as Navbar} from "./Navbar.jsx"
export {default as Home} from "./Home.jsx"
export {default as About} from "./About.jsx"
export {default as Notes} from "./Notes.jsx"
export {default as Login} from "./Login.jsx"
export {default as Alert} from "./Alert.jsx"